spring:
  profiles:
    active:
    - dev
server:
  servlet:
    context-path: /platzi-market/api

---

spring:
  profiles: 
  - dev
  datasource:
    url: jdbc:postgresql://localhost:5432/platzi-market
    username: postgres
    password: postgres
  sql:
    init:
      continue-on-error: true

server:
  port: 8081

---
spring:
  profiles:
  - pdn
  datasource:
    url: jdbc:postgresql://localhost:5432/platzi-market
    username: postgres
    password: platzi
  sql:
    init:
      continue-on-error: true

server:
  port: 80