spring:
  profiles:
    active:
    - dev
server:
  servlet:
    context-path: /platzi-market/api

---

spring:
  config:
    activate:
      on-profile:
      - dev

server:
  port: 8081

---
spring:
  profiles:
  - pdn

server:
  port: 80